# Generated by Django 3.1.1 on 2024-03-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='session',
            new_name='batch',
        ),
    ]
