# Generated by Django 3.1.1 on 2024-03-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20240314_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='batch',
            new_name='session',
        ),
    ]
